// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace Inicio2.Models
{

    /// Database context for the University application, including Identity and student entities.

    public partial class bd_universityContext : IdentityDbContext<ApplicationUser>
    {
        public bd_universityContext(DbContextOptions<bd_universityContext> options) : base(options) { }


        /// Represents the Students table in the database.

        public virtual DbSet<Student> Students { get; set; }

        
        /// Configures the schema needed for the context.
        
        
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.Entity<Student>(entity =>
            {
                entity.HasKey(e => e.Id).HasName("PK__Student__3213E83FC27F82C8");

                entity.Property(e => e.Id)
                    .ValueGeneratedNever()
                    .HasColumnName("id");
                entity.Property(e => e.LastName)
                    .HasMaxLength(32)
                    .IsUnicode(false);
                entity.Property(e => e.Email)
                    .HasMaxLength(32)
                    .IsUnicode(false);
                entity.Property(e => e.FirstName)
                    .HasMaxLength(32)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }
        /// Partial method for additional model configuration.
        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}