// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Inicio2.Models
{
    
    /// Represents a student entity in the system.
    
    public partial class Student
    {
        
        /// Gets or sets the unique identifier for the student.
        
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        
        /// Gets or sets the first name of the student.
        
        public string FirstName { get; set; }

        
        /// Gets or sets the last name of the student.
        
        public string LastName { get; set; }

        
        /// Gets or sets the email address of the student.
        
        public string Email { get; set; }
    }
}